version: '3'

services:
 #Mongodb service
 db:
  container_name: db_container
  image: mongo:latest
  restart: always
  ports:
    - "27017:27017"
  volumes:
    - db:/data/db

# Web service
 web:
    image: node:alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
    command: >
      sh -c "npm i &&
             npm start"

volumes:
  db: {}